import { formatarMoeda } from "@/lib/utils";

/** O contrato distingue Integral/Contraturno/Tarde, mas o schema só tem
 * Turma.turno = MANHA | TARDE — infere pelo nome da turma antes de cair pro
 * turno cru (ver nota no fim de lib/gerarContratoPdf.ts). Compartilhado entre
 * a API (valor inicial) e o modal de revisão (mesma lógica, cliente pode
 * trocar à mão se a turma real for diferente do que o nome sugere).
 * Observação: "Manhã" e "Contraturno" são a mesma coisa pra escola (aluno que
 * só fica o turno da manhã é chamado de "Contraturno") — não existe um 4º
 * rótulo "Manhã" separado. */
export function turnoDoContrato(turmaNome: string, turno: "MANHA" | "TARDE"): DadosContratoTexto["turnoLabel"] {
  const nome = turmaNome.toLowerCase();
  if (nome.includes("integral")) return "Integral";
  if (nome.includes("contraturno")) return "Contraturno";
  return turno === "MANHA" ? "Contraturno" : "Tarde";
}

export type DadosContratoTexto = {
  anoLetivo: number;
  valorMensalidade: number;
  /** MANHA/TARDE (Turma.turno) — só um dos 3 turnos do contrato real (o outro,
   * "Integral", não existe como campo próprio ainda; ver nota no fim de
   * lib/gerarContratoPdf.ts). Quem chama já resolve pro rótulo certo. */
  turnoLabel: "Tarde" | "Integral" | "Contraturno";
};

/** A Cláusula 11ª só distingue 2 modalidades de cobrança — Integral ou
 * Reduzido (Tarde/Contraturno contam como "Reduzido", já que é meio período
 * de qualquer forma) — diferente do turnoLabel, que é mais granular (usado na
 * Ficha de Matrícula pra dizer QUAL turno o aluno frequenta). */
function modalidadeCobranca(turnoLabel: DadosContratoTexto["turnoLabel"]): "Integral" | "Reduzido" {
  return turnoLabel === "Integral" ? "Integral" : "Reduzido";
}

/** Texto fixo do contrato — modelo real da escola (Guntzel & Proensa LTDA -
 * ME / "Carinha de Anjo"), atualizado pra versão 2027 (com Serviço de
 * Alimentação Escolar cobrado à parte, taxa de cuidado estendido e taxa de
 * troca de turno). Usado tanto pra gerar o PDF (lib/gerarContratoPdf) quanto
 * pra pré-visualização na tela (GerarContratoModal). Só 3 coisas variam pelo
 * aluno: ano letivo, valor da mensalidade e turno — o resto é cláusula fixa,
 * igual em todo contrato assinado pela escola. */
export function montarClausulas(d: DadosContratoTexto): string[] {
  const modalidade = modalidadeCobranca(d.turnoLabel);
  const marcaModalidade = (rotulo: "Integral" | "Reduzido") => (modalidade === rotulo ? "(X)" : "(   )");

  return [
    `CONTRATADA: Guntzel & Proensa LTDA - ME, pessoa jurídica de direito privado inscrita no CNPJ sob o nº 12.614.675/0001-00, com sede na Rua José Manhago, nº194, bairro Camobi na cidade de Santa Maria – RS, neste ato representado por sua sócia. A ficha de matrícula, devidamente preenchida e assinada pelas partes, substitui o preenchimento dos campos de identificação do contrato e passa a ser parte integrante do presente, juntamente com o Regimento Escolar e Proposta Pedagógica.`,
    `CLÁUSULA 1ª: O responsável acima qualificado neste Contrato, doravante denominado CONTRATANTE, e a Escola de educação infantil Carinha de Anjo, doravante denominada somente CONTRATADA, representada por seu representante legal, celebram o presente Contrato de prestação de serviços educacionais, sendo os serviços ministrados em conformidade com o previsto na legislação de ensino em vigor, com seu regimento interno e seu planejamento pedagógico durante o ano de ${d.anoLetivo}.`,
    `§1°- O presente Contrato é celebrado sob a égide dos Artigos 206, Incisos II e III e 209 da Constituição Federal, sendo certo que os valores citados nas cláusulas e condições que seguem ao presente instrumento são de prévio conhecimento do CONTRATANTE, com base nos termos da Lei 8.078/90, Lei 9870/99, Lei 9394/96 (Lei de Diretrizes e Bases da Educação) as quais poderão, a qualquer tempo, alterar, suprimir ou acrescentar direitos e deveres às PARTES, mesmo no curso da extensão do Contrato.`,
    `§2°- A prestação dos serviços educacionais, objeto deste Contrato têm seu início na data da assinatura do mesmo e seu término no último dia letivo previsto no Calendário Escolar de ${d.anoLetivo} da CONTRATADA.`,
    `CLÁUSULA 2ª: A CONTRATADA se obriga a ministrar ensino através de aulas e demais atividades escolares, devendo o plano de estudos, programas e calendário estarem em conformidade com o disposto na legislação em vigor e de acordo com o seu Plano Escolar no período de janeiro a dezembro de cada ano. Ao firmar o presente, o CONTRATANTE submete-se ao regimento escolar e às demais obrigações constantes na legislação aplicável à área de ensino e, ainda, às emanadas de outras fontes legais, desde que regulem supletivamente a matéria, inclusive o regimento Escolar e a Proposta Pedagógica.`,
    `CLÁUSULA 3ª: É de inteira e exclusiva responsabilidade da CONTRATADA a orientação técnica sobre a prestação dos serviços de ensino, no que se refere à indicação de professores, escolha do material didático, fixação da carga horária, marcação do calendário escolar, orientação didático-pedagógica, além de outras providências que as atividades docentes exijam.`,
    `CLÁUSULA 4ª: É obrigatório à CONTRATADA fornecer ao aluno certificados de assiduidade e conclusão, alimentação, apoio e acompanhamento nutricional, profissionais qualificados e 550m2 de playground diversificado, observadas as condições e os valores previstos para o Serviço de Alimentação Escolar na Cláusula 12ª.`,
    `CLÁUSULA 5ª: Obriga-se o CONTRATANTE a fazer com que o aluno cumpra o Regimento Escolar, o Calendário Escolar e os horários estabelecidos pela Escola, assumindo total responsabilidade pelos problemas advindos da não observância destes.`,
    `CLÁUSULA 6ª: O horário de funcionamento regular da escola para os alunos de cada turno está especificado no Regimento Escolar. Caso o aluno permaneça nas dependências da escola após o término do seu turno, será devido pelo CONTRATANTE o pagamento de um valor adicional referente ao serviço de cuidado estendido, fixado em R$ 25,00 (vinte e cinco reais) por cada fração de 15 (quinze) minutos de permanência.`,
    `§1°- O aluno deverá estar presente no turno em que estiver matriculado, podendo comparecer em turno inverso somente mediante pagamento de taxa no valor de R$85,00 (oitenta e cinco reais), aviso prévio de 24 horas e tendo vaga disponível.`,
    `§2°- Obriga-se o CONTRATANTE a fazer com que o aluno respeite os horários de entrada e saída, não sendo permitida a entrada após às 10h para alunos matriculados no turno matutino, integral ou contraturno e após 13h30min para alunos matriculados no turno vespertino e também não sendo permitida a saída antes das 17h30min para alunos matriculados no turno vespertino, integral ou contraturno, exceto com aviso prévio via agenda ou telefonema, podendo a escola autorizar ou não a entrada ou saída do aluno.`,
    `CLÁUSULA 7ª: O CONTRATANTE está ciente da obrigatoriedade do uso completo do uniforme escolar por parte do aluno a partir do maternal I, bem como da aquisição de todo o material escolar exigido no início do ano letivo, assumindo inteira responsabilidade por qualquer fato que venha prejudicar o aluno pelo descumprimento desta obrigação e não configurando essa aquisição, em hipótese nenhuma, como parte integrante da anuidade aqui contratada.`,
    `CLÁUSULA 8ª: A CONTRATADA não se responsabiliza pela perda de objetos dos alunos, inclusive celulares ou outros objetos eletrônicos, cabendo ao aluno e aos seus responsáveis a responsabilidade pelos mesmos.`,
    `CLÁUSULA 9ª: O CONTRATANTE, ao assinar o termo de matrícula (Ficha de matrícula), autoriza expressamente a CONTRATADA a utilizar a imagem do aluno (em fotos e vídeos) em materiais de divulgação institucional e pedagógica da escola, exclusivamente para fins de promoção de suas atividades, podendo vinculá-las em suas redes sociais, website oficial e material impresso. Esta autorização é concedida a título gratuito e poderá ser revogada a qualquer momento mediante comunicação por escrito à secretaria da escola.`,
    `CLÁUSULA 10ª: A configuração formal do ato de matrícula e da celebração do Contrato de prestação de serviços educacionais se procede pelo preenchimento e assinatura do formulário próprio fornecido pela Escola denominado "Ficha de Matrícula" que, desde já, fica fazendo parte integrante deste Contrato. A matrícula é considerada concluída quando as partes assinarem a ficha de matrícula e o presente Contrato e o CONTRATANTE pagar a primeira parcela para confirmação de vaga, assim como entregar a documentação exigida pela CONTRATADA.`,
    `Parágrafo Único- A primeira parcela informada na cláusula 11º deste instrumento será cobrada no ato da matrícula e tem caráter de sinal, arras e princípio de pagamento, razão pela qual não será devolvida, no todo ou em parte no caso de desistência por parte do CONTRATANTE, sendo imprescindível sua quitação para celebração e concretização do presente Contrato.`,
    `CLÁUSULA 11ª: O valor da prestação dos serviços educacionais, correspondente ao turno contratado, será informado na Ficha de Matrícula e no quadro financeiro do presente contrato, podendo o CONTRATANTE efetuar o pagamento à vista ou em até 13 (treze) parcelas, conforme as condições financeiras estabelecidas pela CONTRATADA. O valor da prestação educacional não inclui o Serviço de Alimentação Escolar previsto na Cláusula 12ª. Mensalidade contratada: ${d.valorMensalidade > 0 ? formatarMoeda(d.valorMensalidade) : "a definir"}.`,
    `§1°– O presente contrato e os valores estipulados na cláusula anterior se referem à modalidade de atendimento indicada na Ficha de Matrícula: ${marcaModalidade("Integral")} Turno Integral Infantil    ${marcaModalidade("Reduzido")} Turno Reduzido Infantil.`,
    `§2°- O vencimento a partir da segunda parcela será sempre no dia ____ de cada mês iniciando no mês de __________________ do corrente ano ou no primeiro dia útil subsequente, em virtude de feriados, sábados e domingos.`,
    `§3°- O pagamento das parcelas mensais deverá ser efetuado através de boletos bancários enviados via agenda, não sendo aceito pagamento em espécie ou cheque.`,
    `CLÁUSULA 12ª: DO SERVIÇO DE ALIMENTAÇÃO ESCOLAR – O Serviço de Alimentação Escolar é contratado separadamente da prestação dos serviços educacionais e integra, de forma obrigatória, a modalidade de atendimento escolhida pelo CONTRATANTE, uma vez que a alimentação faz parte da rotina de permanência do aluno na escola. O serviço é prestado conforme cardápio elaborado e acompanhado pela Nutricionista responsável e compreende as refeições e lanches correspondentes ao turno frequentado pelo aluno.`,
    `Parágrafo 1º – Para o Turno Reduzido, o Serviço de Alimentação Escolar terá o valor de R$ 300,00 (trezentos reais) mensais e compreenderá 02 (dois) lanches diários, conforme o turno frequentado pelo aluno.`,
    `Parágrafo 2º – Para o Turno Integral, o Serviço de Alimentação Escolar terá o valor de R$ 400,00 (quatrocentos reais) mensais e compreenderá 02 (dois) lanches no período da manhã, 01 (um) almoço e 02 (dois) lanches no período da tarde.`,
    `Parágrafo 3º – Os valores do Serviço de Alimentação Escolar correspondem ao custeio do serviço e consideram custos fixos e variáveis necessários à sua prestação, incluindo, entre outros, mão de obra, nutricionista, insumos alimentícios, gás, água, energia, higiene, manutenção e demais despesas diretamente relacionadas à alimentação escolar. Os valores serão discriminados separadamente da prestação educacional e não constituem cobrança facultativa para o aluno matriculado na respectiva modalidade de atendimento.`,
    `Parágrafo 4º – O Serviço de Alimentação Escolar será cobrado mensalmente durante o período de prestação do serviço, de acordo com a modalidade contratada. A ausência do aluno, por qualquer motivo, não implicará desconto ou restituição, observadas as demais disposições deste Contrato.`,
    `Parágrafo 5º – Não é permitido ao aluno trazer lanche ou almoço para substituição das refeições fornecidas pela Escola, ressalvadas situações de restrição alimentar comprovada por laudo médico, que serão previamente avaliadas e alinhadas entre a família e a coordenação da Escola.`,
    `CLÁUSULA 13ª: Não estão incluídos na prestação dos serviços educacionais nem no Serviço de Alimentação Escolar, dentre outros, os custos concernentes à identidade estudantil, expedição da segunda via de documentos, excursões, festas, atividades extracurriculares, fornecimento de materiais paradidáticos, entre outros, cujas cobranças serão feitas caso a caso.`,
    `CLÁUSULA 14ª: Também não estão incluídos na anuidade do Contrato os danos materiais que o aluno, dolosa ou culposamente, possa vir a causar à Escola.`,
    `CLÁUSULA 15ª: O não pagamento da parcela no vencimento sujeitará o CONTRATANTE ao pagamento do valor principal acrescido de multa de 2% (dois por cento), juros de mora de 1% (um por cento) ao mês e correção monetária pelo IGPM. Em caso de cobrança realizada por intermédio de advogado, serão também devidos os honorários advocatícios, fixados em 10% (dez por cento) para cobrança extrajudicial e 20% (vinte por cento) para a judicial.`,
    `CLÁUSULA 16ª: Em caso de inadimplência no pagamento de qualquer das parcelas previstas por mais de 90 (noventa) dias, a CONTRATADA poderá adotar pelo encaminhamento do débito ao Serviço de Cadastro de Consumidores Inadimplentes (SPC, SERASA), Cartório de Protesto de Títulos e/ou Assessoria Jurídica, conforme art. 43, parágrafo segundo da Lei 8.078 de setembro de 1990 (Código de Defesa do Consumidor) ficando o CONTRATANTE obrigado ao pagamento de todos os custos inerentes aos casos acima citados.`,
    `Parágrafo único- Em caso de inadimplemento por não pagamento de qualquer das parcelas previstas por mais de 90 (noventa) dias o CONTRATANTE além do que consta na cláusula 16° também poderá perder toda e qualquer gratuidade ou desconto dos quais seja eventualmente beneficiário.`,
    `CLÁUSULA 17ª: O CONTRATANTE não poderá se eximir do pagamento das parcelas aqui ajustadas, no caso de separação com o cônjuge, onde este por força da separação ficou obrigado pelo pagamento destas parcelas, objeto deste contrato.`,
    `CLÁUSULA 18ª: A ausência do aluno nas aulas, ou sua desistência ou evasão sem expressa e antecipada comunicação, não exime o CONTRATANTE dos pagamentos nem rescinde o Contrato de prestação de serviços educacionais.`,
    `CLÁUSULA 19ª: O presente contrato poderá ser rescindido pelo CONTRATANTE mediante requerimento escrito via agenda escolar (recados) ou protocolado na secretaria da escola, com antecedência mínima de 30 (trinta) dias.`,
    `§1° - Caso a rescisão ocorra após o início do ano letivo, será devida pelo CONTRATANTE uma multa rescisória correspondente a 10% (dez por cento) do valor das parcelas vincendas (a vencer), a fim de cobrir custos administrativos e o planejamento de vagas da CONTRATADA.`,
    `§2° - A rescisão só será efetivada após a quitação de todas as parcelas vencidas e da multa rescisória prevista no parágrafo anterior, momento no qual a CONTRATADA fornecerá a documentação para transferência.`,
    `CLÁUSULA 20ª: A partir da assinatura deste Contrato, o CONTRATANTE só poderá rescindi-lo após pagamento de no mínimo 03 (três) parcelas cabendo ainda, nesse caso, o cumprimento do prazo de aviso prévio da cláusula 19ª. O prazo de 30 dias de aviso também deve ser dado em caso de troca de turno em tendo vaga.`,
    `Parágrafo Único: Em ocorrendo a rescisão, o aluno só poderá ser desligado da instituição após a quitação dos saldos em aberto, obrigando-se a CONTRATADA a fornecer toda documentação que o aluno necessite para efetuar transferência de escola.`,
    `CLÁUSULA 21ª: A renovação do Contrato de prestações de serviços será realizada em período programado pela CONTRATADA, e só poderá ser feita se respeitadas as condições estipuladas na nova matrícula.`,
    `Parágrafo Único: A CONTRATADA não estará obrigada a renovar a matrícula do aluno, para o período letivo posterior, caso haja parcelas em aberto conforme preconiza o Art. 5º da Lei 9.870/99, independente de quem seja o responsável financeiro, ou ainda, em caso de descumprimento do regimento interno, ou das cláusulas e condições deste Contrato.`,
    `CLÁUSULA 22ª: A inadimplência de qualquer obrigação contida neste instrumento assegura à parte inocente o direito de não mais contratar com a parte infratora os serviços educacionais, principal e especialmente, no que se refere ao período seguinte ao término da vigência deste Contrato.`,
    `CLÁUSULA 23ª: A validade deste instrumento está condicionada à sua assinatura e realização da matrícula do aluno. O CONTRATANTE se responsabiliza pelos dados declarados, comprometendo-se a informar à CONTRATADA qualquer alteração ou mudança de dados presentes neste Contrato.`,
    `CLÁUSULA 24ª: Na ocorrência de eventos de caso fortuito ou força maior que impeçam a prestação de serviços de forma presencial (tais como epidemias, desastres naturais, ordens governamentais etc.), a CONTRATADA se compromete a dar continuidade aos serviços educacionais de forma remota ou por meios alternativos, conforme seu plano pedagógico e as diretrizes dos órgãos de ensino. A migração para o regime remoto não implicará em suspensão do contrato ou isenção do pagamento das mensalidades, uma vez que a prestação de serviço continuará sendo executada.`,
    `CLÁUSULA 25ª: DO TRATAMENTO DE DADOS – PRINCÍPIOS DA PROTEÇÃO DOS DADOS. Toda e qualquer prática de tratamento de dados pessoais no âmbito da CONTRATADA/ESCOLA condiz com a natureza, o escopo e a missão institucional, mas, sobretudo, é realizada em conformidade com a Lei. Os dados dos CONTRATANTES e do aluno MENOR, por seu responsável legal.`,
    `25.1. LICITUDE DO TRATAMENTO DE DADOS. A CONTRATADA/ESCOLA fará a coleta, conservação e tratamento de dados do(s) CONTRATANTES e do aluno MENOR com atenção aos direitos dos titulares de dados pessoais, aos requisitos contratuais e legais e por imposição do cumprimento de obrigações legais e para cumprimento do presente contrato, mediante amplo e irrestrito consentimento do(s) CONTRATANTES e do aluno MENOR.`,
    `25.2. RESPONSÁVEL PELO TRATAMENTO. A CONTRATADA/ESCOLA devidamente qualificada neste contrato será a Responsável pelo tratamento dos dados do(s) CONTRATANTES e do aluno MENOR cujo processamento de dados será realizado internamente ficando a CONTRATADA/ESCOLA expressamente autorizada a, caso assim o entenda, efetuar esse processamento externamente, responsabilizando-se pela confidencialidade dos dados coletados.`,
    `25.3. COLETA DOS DADOS. Será efetuada pelo(s) CONTRATANTES e pelo aluno MENOR diretamente através do fornecimento espontâneo de dados inseridos no Requerimento de matrícula e termo de adesão ao Contrato de Prestação de Serviços Educacionais no ano letivo ${d.anoLetivo} incluindo preenchimento de impressos pela CONTRATADA/ESCOLA.`,
    `25.4. FINALIDADES DO TRATAMENTO DOS DADOS. CONTRATADA/ESCOLA fará o tratamento de dados com as seguintes finalidades: GESTÃO CONTABILÍSTICA, FISCAL E ADMINISTRATIVA incluindo gestão econômica, gestão fiscal, gestão de faturação, gestão de clientes, gestão de cobranças e pagamentos.`,
    `25.5. DADOS PESSOAIS CONTIDOS NO REGISTRO E CONSENTIMENTO. A CONTRATADA/ESCOLA coletará dados indispensáveis para a finalidade do Contrato de Prestação de Serviços Educacionais que incluem nome, endereço residencial e comercial, contatos telefônicos e endereços eletrônicos, data de nascimento, gênero, filiação, estado civil, naturalidade, nacionalidade, identificação civil (RG), número do cadastro de Pessoa Física (CPF), profissão e parentesco com o aluno, dados estes tanto do(s) CONTRATANTES e do aluno MENOR, e ainda, especificamente quanto ao aluno menor dados quanto ao estado de saúde, convênio médico vinculado ao aluno menor, os CONTRATANTES e o aluno MENOR consentem, neste ato, o tratamento destes dados pela CONTRATADA/ESCOLA.`,
    `25.6. EXCEÇÕES. Excluem-se do conceito de privacidade a informação: a) pública por determinação legal; b) pública para o tratamento e uso compartilhado da dados de execução de políticas públicas; c) objeto de decisão judicial transitada em julgado, pela divulgação ou exibição da mesma; d) ostensiva com dever de segurança ativa; e) ostensiva com dever de segurança passiva; f) já dada, por outros meios, ao conhecimento público; g) necessária à proteção da vida ou da incolumidade física de pessoais; h) necessária à tutela da saúde e i) dados cadastrais necessários à legítima atuação da CONTRATADA/ESCOLA em atendimento à execução do Contrato de Prestação de serviços firmado entre as partes.`,
    `25.7. COMUNICAÇÃO DOS DADOS A TERCEIROS. A CONTRATADA/ESCOLA apenas irá comunicar ou transferir em parte ou na sua totalidade os dados pessoais do(s) CONTRATANTES e do aluno MENOR a entidades públicas e ou privadas sempre que tal decorra de obrigação legal e ou seja necessário para cumprimento deste ou outros contratos ficando para tal expressamente autorizada pelo(s) CONTRATANTES e pelo aluno MENOR.`,
    `25.8. PRAZO DE CONSERVAÇÃO DOS DADOS. A CONTRATADA/ESCOLA conservará os dados do(s) CONTRATANTES e do aluno MENOR pelos prazos necessários a dar cumprimento às obrigações legais e conservará os dados apenas durante o período necessário à prossecução das finalidades da coleta ou do tratamento posterior, garantindo a sua confidencialidade.`,
    `25.9. DIREITOS DO TITULAR DOS DADOS. O(s) CONTRATANTES e o aluno MENOR poderão solicitar à CONTRATADA/ESCOLA e está, salvo impedimento legal, irá salvaguardar os direitos do(s) CONTRATANTES e do aluno MENOR de acesso aos dados pessoais que lhe digam respeito, bem como, a sua retificação, cancelamento ou exclusão, a limitação do tratamento, explicação sobre o uso dos dados, requisição de uma cópia da integralidade dos seus dados e o direito de se opor ao tratamento, bem como, do direito à portabilidade dos dados. E ainda o direito de retirar consentimento em qualquer altura, sem comprometer a licitude do tratamento efetuado com base no cumprimento de obrigações legais ou com base no consentimento previamente dado para o cumprimento do contrato, e também o direito de reclamação sobre o tratamento de dados junto à Autoridade Nacional de Proteção de Dados.`,
    `25.10. SEGURANÇA NO TRATAMENTO DOS DADOS. Tendo em conta as técnicas mais avançadas, os custos de aplicação e a natureza, o âmbito, o contexto e as finalidade do tratamento, bem como os riscos, de probabilidade e gravidade variável, para os direitos e liberdades das pessoas singulares, a CONTRATADA/ESCOLA aplica as medidas técnicas e organizacionais adequadas para assegurar um nível de segurança adequado ao risco, proporcionando a segurança das informações coletadas.`,
    `25.11. VIOLAÇÃO DE DADOS PESSOAIS. Em caso de violação de dados pessoais a CONTRATADA/ESCOLA notificará esse fato à Autoridade Nacional de Proteção de Dados nos termos e condições previstos na lei. Se essa violação for suscetível de implicar um elevado risco para os direitos e liberdades do titular comunicará esse fato, nos termos e condições previstos na lei.`,
    `CLÁUSULA 26ª: CONTRATADA E CONTRATANTE(S) declaram que concordam com a forma de contratação validando a assinatura manual ou digitalizada da CONTRATADA e testemunhas no presente instrumento e declaram a contratação e aceitação das cláusulas do presente contrato através da assinatura dos CONTRATANTES(S) no requerimento de matrícula.`,
    `CLÁUSULA 27ª: Para dirimir quaisquer questões oriundas do Contrato, as partes elegem o foro da comarca de Santa Maria RS.`,
    `E por estarem às partes de acordo com todos os termos e condições do presente instrumento, assinam o presente Contrato, em duas vias de igual teor e forma, juntamente com duas testemunhas, para que produza seus jurídicos efeitos.`,
  ];
}
